//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

#[cfg(feature = "server")]
pub mod prelude;

#[cfg(feature = "server")]
pub mod app_role;

#[cfg(feature = "server")]
pub mod employee;

#[cfg(feature = "server")]
pub mod users;
