//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

#[cfg(feature = "server")]

pub use super::app_role::Entity as AppRole;
pub use super::employee::Entity as Employee;
pub use super::users::Entity as Users;
