//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

#[cfg(feature = "server")]

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub role_id: i32,
    pub created_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub employee_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_role::Entity",
        from = "Column::RoleId",
        to = "super::app_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppRole,
    #[sea_orm(
        belongs_to = "super::employee::Entity",
        from = "Column::EmployeeId",
        to = "super::employee::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Employee,
}

impl Related<super::app_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppRole.def()
    }
}

impl Related<super::employee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employee.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
